### ISSUE TITLE
Not working with minecraft 

### ISSUE THREAD

**Issue by lattermatter** [anhgelus/manhunt-mod#2]
For some reason, the mod doesnt work in my Minecraft environment. When I try to type /manhunt, the command is not recognized. Here is the mods folder:
![image](https://github.com/user-attachments/assets/9fe97782-fdc2-403c-ab41-ed356cf37326)

I am not sure what the problem is, I tried both versions of the mod too

**Comment by anhgelus** [comment]
This mod cannot be run on a client. It has to be on a server. Tries to use it on a server and it should work.

I decided this because this mod is useless in single-player.
